name: bill_snowflake
version: 1.0.0
profile: bill_snowflake
config-version: 2

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]

models:
  bill_snowflake:
    staging:
      +schema: STAGING
      +materialized: view
    intermediate:
      +schema: INTERMEDIATE
      +materialized: view
    marts:
      +schema: MARTS
      +materialized: table