bill_snowflake:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: dtc82906.us-east-1
      user: PAVANKOLLI0601
      password: Sublime@06010601
      role: ACCOUNTADMIN
      warehouse: COMPUTE_WH
      database: BILL_DEMO
      schema: RAW
      threads: 4